### ISSUE TITLE
Question: patch performance.

### ISSUE THREAD

**Issue by hyrious** [aidenybai/million#107]
The [patch algorithm with no _delta_ info](https://github.com/aidenybai/million/blob/372294f7088c7f65bd17d9afc37677823d8e763d/src/patch.ts#L80-L87) is quite simple and it's easy to make a worst case.

e.g. If we patch `A B C` &rarr; `X A B C`, this algorithm would compare & patch old_C with B, then old_B with A, then old_A with X, then insert C (4 steps). While the best way to do this is one step: insert X before old_A.

Better algorithms can be found in [inferno](https://github.com/infernojs/inferno/blob/master/packages/inferno/src/DOM/patching.ts), [solid](https://github.com/solidjs/solid/blob/main/packages/solid/store/src/modifiers.ts), [fre](https://github.com/yisar/fre/blob/master/src/reconcile.ts) and [vue](https://github.com/vuejs/vue-next/blob/master/packages/runtime-core/src/renderer.ts). (The solid.js one should be easiest to read.)

You may argue that using _delta_ is a better choice, it's the same to say we left a blank in dom diffing to let other programmers write. Besides, if we're making some ui framework which can analyse _template_ like vue or svelte, then the delta info can be cached and the performance is the best. -- only if we have _template_. If we choose to work like react, whose layout is determined at runtime (the render() func), then we get no way to pre calculate the delta, neither caching it.

Would you implement a better patch algorithm, or leave it as is?

**Comment by aidenybai** [comment]
Good point, I've been trying to work on this issue but my knowledge + experience with algorithms is too little to pull something off like this.

I think deltas are still a viable feature, as it can be very useful, but I also agree with you the current patch algorithm can be refactored to be significantly more performant.

I've tried [to copy over and monkey-patch the diffing algorithm](https://github.com/aidenybai/million/blob/b431313022dbb7efc7fe269a1c0623d1a6a923b9/src/patch.ts#L164) from snabbdom, but only for keyed diffing. I chose this because I think generally if you want something to be performant, you should generally just use keys (if deltas don't apply). Also, it is somewhat difficult to determine whether two vnodes without a keys are equal without deep comparision (also not performant).

The snabbdom copied solution was unsuccessful, as when I ad-hoc benchmarked it, it was much slower than even worst case patching. 

I would love to implement a better patch algorithm, but my current skills and understanding on how to isn't there to figure out how to implement it correctly. I'll definetely take a look at the resources you provided, and if you want to help, feel free to if you have a bit of time.

**Comment by loteoo** [comment]
I'd add [superfine](https://github.com/jorgebucaran/superfine/blob/main/index.js) to the list of libraries to checkout for inspiration for this issue.

I'm using million for a test project and am not really using the delta features so far (I'd rather wait for an automated solution and I'm in no rush). I like million over some other libraries because I can easily read it's clean typescript codebase in case I need to change / fork it ❤️. Some elements seem to be re-created a lot at the moment so I'm interested in this issue as well 😄!

**Comment by aidenybai** [comment]
Update: currently have a prototype working in `efficient-keyed-diffing` branch

**Comment by aidenybai** [comment]
Merged in #109, releasing in next minor version
