### ISSUE TITLE
Bug: createElement doesn't support Fragment as root VNode.

### ISSUE THREAD

**Issue by SukkaW** [aidenybai/million#160]
### Describe the bug

The return type of `Fragment` is `VNode[]`.

https://github.com/aidenybai/million/blob/7ccc5f021df8ea384d5e03da165633238b52529f/src/jsx.ts#L110

However, `createElement` doesn't support passed in an array of VNode:

https://github.com/aidenybai/million/blob/1ea5443220a9d7caf1512862a3b24e968548e638/src/createElement.ts#L10-L13

### To Reproduce

```jsx
import { createElement } from 'million';

function Example() {
  return (
    <>
      {
        ['A', 'B', 'C'].map(i => (<div>{i}</div>))
      }
    </>
  );
}

document.body.appendChild(createElement(Example));
```

### Expected behavior

Render `<div>A</div><div>B</div><div>C</div>` instead of `<undefined></undefined>`.

### Operating System

Not applicable

### Browser

Not applicable

**Comment by aidenybai** [comment]
Here's what I'm a bit conflicted about with Fragment -- and I'd like your feedback on this:

Million.js is a Virtual DOM library, and is intended just to be a Virtual DOM library. This means concepts like state, components, etc need to be developed by the user or various [library explorations upon million](https://github.com/aidenybai/hacky). I'm hesitant to add multiroot support directly to the million codebase (because libraries generally will develop their own custom mounting implementation), yet I want some level of support on the JSX level.

Here's a potential band aid to the problem -- make Million.js's `jsx-runtime` just wrap the children in a `div` element so the `Fragment` is just syntatic sugar. This way, you don't face the issue of `undefined` elements when using Fragment, and various library developers can create their own multi-root mounting schemes upon Million

**Comment by SukkaW** [comment]
> Million.js is a Virtual DOM library and is intended just to be a Virtual DOM library. This means concepts like state, components, etc need to be developed by the user or various library explorations upon million.

Yeah, I am fully aware of that, and I am managing state myself, and let million to only does DOM manipulation.

> make Million.js's `jsx-runtime` just wrap the children in a `div` element so the `Fragment` is just syntactic sugar.


Sometimes it will produce invalid HTML, just as React's `<table> example` [in their documentation](https://reactjs.org/docs/fragments.html#motivation):

```js
// Minimum example
const Columns = () => (
  <>
    <td>Hello</td>
    <td>World</td>
  </>
);

const Table = () => (
  <table>
    <tr>
      <Columns />
     </tr>
   </table>
);

// <Table /> will output invalid html:
/*
  <table>
    <tr>
      <div>
        <td>Hello</td>
        <td>World</td>
      </div>
     </tr>
   </table>
 */
```

Yeah, Of course, I won't ask Million to have React's `keyed Fragments` or *future additional attributes*. But `VNode[]` is still a possible case here.

**Comment by aidenybai** [comment]
I'll leave this issue here for a day and see if there is any additional feedback from others. If there is not, i'l proceed in adding multi-element support for createElement

**Comment by aidenybai** [comment]
After some thought and discussion with friends, I think it may be best to leave this out of Million.js' featureset. I say this because this can fundamentally change some parts of the API -- How would `createElement` deal with a fragment? Just return an array of elements in which the user needs to iterate over and `appendChild` anyway? 

Additionally, the patch system would also need to be reworked, which is feel can make performance (marginally) worse and just less elegant in general. However, this isn't to say Million will hard discourage the implementation of some sort of Fragment system for the live DOM. For instance, one could create their own `mount` system if need be.

Let me know if you think my opinion can be corrected or have any questions.

**Comment by SukkaW** [comment]
Agreed, that's fair.

**Comment by aidenybai** [comment]
After experimenting with this for the last couple of days -- this seems to be possible with minimal changes and no longer needs a mounting system. Pushing soon!

**Comment by gustavopch** [comment]
@aidenybai So passing multiple root-tags to `html` isn't (and won't be) supported, right?
```js
// This results in an array of virtual nodes instead of a single one
const vNodes = html`
  <p>Foo</p>
  <p>Bar</p>
`

render(document.body, vNodes)
```

**Comment by aidenybai** [comment]
Fragment will (likely) never be supported by the underlying Virtual DOM, but the react compat package will support Fragment
