### ISSUE TITLE
Add compatibility with Gatsby, Remix, etc.

### ISSUE THREAD

**Issue by joebentaylor1995** [aidenybai/million#322]
As the title suggested, can this be used in a Gatsby project?

**Comment by aidenybai** [comment]
technically yeah. just use the webpack plugin inside your gatsby plugin instead https://millionjs.org/docs/compiler

**Comment by tobySolutions** [comment]
Can we close this issue now @aidenybai?

**Comment by tobySolutions** [comment]
We have support for Gatsby now @aidenybai. Not sure about Remix yet @joebentaylor1995.

**Comment by aidenybai** [comment]
We can't get Remix support because they don't have a plugin system

**Comment by SukkaW** [comment]
@aidenybai @tobySolutions I believe we can close this issue now since Million already provides plugins for Webpack and Next.js, while Gatsby can use Million's Webpack plugin.

As for Remix, IIRC Remix uses the esbuild under the hood. And according to the Remix Team (https://github.com/remix-run/remix/issues/717) and here I quote:

> ... we do not plan on opening up our compiler. Our usage of esbuild is an implementation detail.

That's to say, Remix will most likely **never** provide an option to manipulate its compiler behavior/configuration, which also means **it is impossible for anyone to create a third-party plugin to change Remix's compiler option in any foreseeable future**.

**Comment by joebentaylor1995** [comment]
Is there any documentation on how to enable this in gatsby? I feel clueless setting this up

**Comment by tobySolutions** [comment]
> Is there any documentation on how to enable this in gatsby? I feel clueless setting this up

Sure, in the docs. We show you how you can add the compiler to make sure that you can enable it in Gatsby. 

To use it though, you can test the `block()` on the components in your application. 

Let me know if you have any other issues. Also, let me know if the documentation doesn't work.

**Comment by joebentaylor1995** [comment]
Could you link me to this? I can’t seem to find thisOn 24 May 2023, at 02:15, Tobiloba Adedeji ***@***.***> wrote:﻿

Is there any documentation on how to enable this in gatsby? I feel clueless setting this up

Sure, in the docs. We show you how you can add the compiler to make sure that you can enable it in Gatsby.
To use it though, you can test the block() on the components in your application.
Let me know if you have any other issues. Also, let me know if the documentation doesn't work.

**Comment by aidenybai** [comment]
@joebentaylor1995 

https://million.dev/docs/install#use-the-compiler

```jsx
const million = require('million/compiler');
 
exports.onCreateWebpackConfig = ({ actions }) => {
  actions.setWebpackConfig({
    plugins: [million.webpack({ mode: 'react-server' })],
  })
}
```
