### ISSUE TITLE
[$300] feat: cross file blocks + ui component library support

### ISSUE THREAD

**Issue by aidenybai** [aidenybai/million#488]
Currently, we only support using `block()` in the same file as the original component, like so:

```jsx
import { block } from 'million/react';

function Component() {
	// ...
}

const ComponentBlock = block(Component);
```

But what if we could do cross file blocks?

```jsx
// file1.jsx
export function Component() {
	// ...
}

// file2.jsx
import { block } from 'million/react';
import { Component } from './file1';

const ComponentBlock = block(Component);
```

And what if we could do this within modules?

```jsx
import { Button } from 'chakraui';

const ButtonBlock = block(Button);
```

For reference, this was my original approach: https://github.com/aidenybai/million/tree/fix/cross-file-blocks. If you're committed to fixing this issue, email me hello@aidenybai.com and we can brainstorm on this

**Comment by oliverloops** [comment]
I'll try to figure it out and see what happens 😅

**Comment by nojiritakeshi** [comment]
@aidenybai 
Is it possible to render as follows, but there is a performance problem?
```ts
import { Row } from "./BlockSample";

function App() {
  const RowB = block(({ adj }: Props) => <Row adjective={adj} />);
  return (
      <RowB adj="aaaaaaa" />
  );
}
```

**Comment by gxanshu** [comment]
> @aidenybai Is it possible to render as follows, but there is a performance problem?
> 
> ```ts
> import { Row } from "./BlockSample";
> 
> function App() {
>   const RowB = block(({ adj }: Props) => <Row adjective={adj} />);
>   return (
>       <RowB adj="aaaaaaa" />
>   );
> }
> ```

```javascript
console.log(block(() => <div />)) // ❌ Wrong
export default block(() => <div />) // ❌ Wrong
 
// 👇👇👇
 
const Block = block(() => <div />) // ✅ Correct
console.log(Block);
export default Block;
```

according to this code example from million's documentations i think it wouldn't work

**Comment by gxanshu** [comment]
React have really a huge ecosystem and its the first preference of any web app but some of the time applications use UI libraries to provide a great experience to the end user. soon in the future million will use in every react project if we able to solve that problem.

**Comment by niomu** [comment]
Maybe that can fix :

```js
const block = (/*args*/) => {
  const vnode =
    typeof fn === 'function' && !!fn.prototype?.isReactComponent
      ? new fn(HOLE_PROXY).render()
      : fn(HOLE_PROXY);
  //...
};
```

**Comment by ashutosh887** [comment]
@aidenybai 
let me work on this 
Please assign

**Comment by renhiyama** [comment]
> @aidenybai Is it possible to render as follows, but there is a performance problem?
> 
> ```ts
> import { Row } from "./BlockSample";
> 
> function App() {
>   const RowB = block(({ adj }: Props) => <Row adjective={adj} />);
>   return (
>       <RowB adj="aaaaaaa" />
>   );
> }
> ```

While this method works, millionjs compiler cannot optimize the component as it doesn't have any access to the real component code, and there's not much performance problem except that you have extra code that does nothing...

**Comment by renhiyama** [comment]
The main issue lies at the code bundlers' level (vite, rollup, webpack, packit, etc.)
Any/Most code bundler's "plugin rules" expects the plugin to work at the file-level. Millionjs compiler doesn't break the rule because it stays and works in/with the same file code that the bundler itself provides. However, this feature implementation requires millionjs compiler to read other files (here in this case would be the imported files and modules) and perform optimizations there.
So what I see is that we need to write bundler-specific code to hack our way around, but then it arises a different problem. Some code bundlers dont have proper "order" of plugins implementation, and most of the code bundlers seem to have different caching mechanisms, and millionjs compiler cannot(?) access/make use of it/follow them.

Considering these severe problems, the time to compile/bundle any code using millionjs might increase a lot as it might recursively run through the same file a lot of times.

**Comment by Wholesomebruh** [comment]
It's open from my side, I don't know how to cancel my attempt.

**Comment by dennismzia** [comment]
is this issue still open? I see it was opened a long time ago.

**Comment by ogil7190** [comment]
@aidenybai Can i try this?

**Comment by skushagra9** [comment]
Hi, please tell me if this issue has not been solved
@aidenybai 
I will definitely work on this

**Comment by skushagra9** [comment]
@tobySolutions please confirm

**Comment by lxsmnsyc** [comment]
I'll work on this one, bounty or not.

**Comment by maisnamraju** [comment]
@Aslemammad can I take up this ticket ?

**Comment by Aslemammad** [comment]
Sure, feel free to.

**Comment by maisnamraju** [comment]
@Aslemammad thanks. Picking it up.

**Comment by vivasvan1** [comment]
@Grenish @riffly @karthiknadar1204 Are you guys still on this?

**Comment by adilkadivala** [comment]
/attempt #488

<div id="algora-attempt" />

<details>
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/clk9g4xwu0002jt0fh4prr4lk/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>

**Comment by adilkadivala** [comment]
hey I need more depth on this issue ?? any one here to explain it ??

do we fix export at the beginning of the component instead of bottom export default ?? 

i mean _Currently_ **components  defined and then exported**, _and we want_ **directly exporting the component along with wrapping it using the block function** ?? as I got..

here is one of them , i have two solution .. 

1. 

currently it is 

_import React, { useState } from 'react';
import { block } from 'million/react';

interface DataConverterState {..} 
.....

const DataConverter: React.FC = block(() => {...}

export default DataConverter;_

so we need to make it

_**export** const DataConverter: React.FC = block(() => {...}_

2. 

**create one file named DataConverteBlock and import in it block and DataConverter, then make like this 

import { block } from 'million/react';
import { DataConverter } from './file1';

const DataConverteBlock = block(DataConverter);**

if not this then please describe in depth..
