### ISSUE TITLE
Kitchen Sink: Build A Stock Price Tracker

### ISSUE THREAD

**Issue by tobySolutions** [aidenybai/million#611]
Build an app that tracks stock prices using a financial data API that you'll add to the kitchen sink. Feel free to use any existing projects of yours or start one from scratch.

For more information about the Kitchen sink; check out:

- https://sink.million.dev/
- https://github.com/aidenybai/million/blob/main/packages/kitchen-sink/README.md  

N.B: **Upon PR review, your usage of Million.js is a plus**

**Comment by Abhishek-Mallick** [comment]
@tobySolutions Could you please assign this to me

**Comment by tobySolutions** [comment]
Sure thing @Abhishek-Mallick!

**Comment by Abhishek-Mallick** [comment]
Hey @tobySolutions 
Please have a look at pull request https://github.com/aidenybai/million/pull/667

There seems to be 4 file changes which is supposed to be one `packages/kitchen-sink/src/examples/stock-prices.tsx`
The rest three file changes was for my previous PR https://github.com/aidenybai/million/issues/625

There are no merge conflicts or dependency issues which can arise

**Comment by Timonwa** [comment]
> Hey @tobySolutions Please have a look at pull request #667
> 
> There seems to be four file changes, which is supposed to be one `packages/kitchen-sink/src/examples/stock-prices.tsx`. The other three file changes were for my previous PR #625
> 
> There are no merge conflicts or dependency issues which can arise

I believe this is happening because,  after creating your first PR,  you were supposed to make a new branch from the  `main branch` for your second PR. But instead,  you created the second branch from your previous one. And since your first PR had not been merged, it now seems like you are solving two PRs in one branch. 

You could delete the codes related to the previous PR from this branch or create a new branch from the `main` branch and open a new PR.

**Comment by tobySolutions** [comment]
Hmm, thanks for the awesome insight @Timonwa! 🙌
