### ISSUE TITLE
[$50] modified state value is not reflected into the input field.

### ISSUE THREAD

**Issue by UzairNoman** [aidenybai/million#680]
### What version of `million` are you using?

2.6.4

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

yarn

### What operating system are you using?

Windows

### What browser are you using?

Chrome

### Describe the Bug

The variable's state get reset when passing empty string but the input field doesn't get emptied. Problem is demonstrated more clearly through a video

https://github.com/aidenybai/million/assets/12785891/abd5b0cc-39e6-4271-bb73-d09643629e80

### What's the expected result?

When resetting the status to empty value, then input field should be reset as well.

### Link to Minimal Reproducible Example

Check the video (easy to reproduce)

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by tobySolutions** [comment]
I'll come back to this issue when I have a better network connectivity

**Comment by vimode** [comment]
I had the same issue, I switched to making my input form an uncontrolled component in #655 

I wasn't sure if its my implementation problem or the way million decides when to pass *updated* props to the child component.

**Comment by tobySolutions** [comment]
I notified core team about this @UzairNoman, @vimode. Thank you both for this. We'll be looking into it.

**Comment by tobySolutions** [comment]
This issue seems to be related to #797.

**Comment by ologbonowiwi** [comment]
Hey folks, as mentioned on [MDN's setAttribute documentation](https://developer.mozilla.org/en-US/docs/Web/API/Element/setAttribute#gecko_notes)
> Using setAttribute() to modify certain attributes, most notably value in XUL, works inconsistently, as the attribute
specifies the default value. To access or modify the current values, you should use the properties. For example, use
Element.value instead of Element.setAttribute().

I've fixed it, opened a PR, and used `el.value` for such cases. It worked successfully here (I tested it against the `github-user-search` example). Let me know if there are any tweaks required for #833 :smile:
